### ISSUE TITLE
MVP Launch Checklist

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#121]
- [x] Update ETL to parse Addresses (API)
- [x] Footer Links and add privacy policy #98 
- [x] Add default image for events with no image #122
- [x] Make backend "stay awake" (API)
- [x] Test add-event form/trello

- [x] Add event URLS to API
- [x] Make API store Timezones in UTC
- [x] Make event page buttons links work #107 
- [x] Allow date range + search query #95
- [x] Update Search Query #118 
- [x] Display Event Start/End times on event details pages #131
- [x] Make add events menu full width on mobile #123
- [x] Fix Date Selector Bug (mobile) #114 
- [x] Add google analytics
- [x] Hide canceled events #160
- [x] Fix today's date bug #150
- [x] solve Image hosting issue (API)
- [x] Fix event dates with late end times (API)

FRONT END PROJECT BOARD:
https://github.com/ResistanceCalendar/resistance-calendar-frontend/projects/1

API PROJECT BOARD:
https://github.com/ResistanceCalendar/resistance-calendar-api/projects/1

**Comment by dorono** [comment]
@InciteDemocracy Looks good off the bat! Do continue my broken record routine on this topic, do you think we should give folks a way to keep in touch via email? Perhaps just collecting email address and zip code so eventually we can implement a system to email out weekly/monthly event listings? Otherwise, folks may drift away from the site after the hype wears off(?). Or perhaps we should see what the other folks think?

**Comment by InciteDemocracy** [comment]
I'm all for it! We could whip something up, or put this at the top of the list for v2. Either way is ok, just not wanting to add too many features and slow down progress.

**Comment by pdw207** [comment]
@InciteDemocracy Have you tested the trello add event page?

**Comment by InciteDemocracy** [comment]
@pdw207 YES, it work works nicely! we just need to fix it on mobile screens #123 and point it at the right trello board.
